/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRetailerIndexRouteImport } from './routes/_authenticated/retailer/index'
import { Route as AuthenticatedRecyclerIndexRouteImport } from './routes/_authenticated/recycler/index'
import { Route as AuthenticatedIndustryIndexRouteImport } from './routes/_authenticated/industry/index'
import { Route as AuthenticatedCollectorIndexRouteImport } from './routes/_authenticated/collector/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedRetailerOrdersRouteImport } from './routes/_authenticated/retailer/orders'
import { Route as AuthenticatedRetailerMarketplaceRouteImport } from './routes/_authenticated/retailer/marketplace'
import { Route as AuthenticatedRecyclerProductsRouteImport } from './routes/_authenticated/recycler/products'
import { Route as AuthenticatedRecyclerInventoryRouteImport } from './routes/_authenticated/recycler/inventory'
import { Route as AuthenticatedIndustrySustainabilityRouteImport } from './routes/_authenticated/industry/sustainability'
import { Route as AuthenticatedIndustryPickupsRouteImport } from './routes/_authenticated/industry/pickups'
import { Route as AuthenticatedIndustryListingsRouteImport } from './routes/_authenticated/industry/listings'
import { Route as AuthenticatedCollectorPickupsRouteImport } from './routes/_authenticated/collector/pickups'
import { Route as AuthenticatedCollectorJobsRouteImport } from './routes/_authenticated/collector/jobs'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetailerIndexRoute =
  AuthenticatedRetailerIndexRouteImport.update({
    id: '/retailer/',
    path: '/retailer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecyclerIndexRoute =
  AuthenticatedRecyclerIndexRouteImport.update({
    id: '/recycler/',
    path: '/recycler/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustryIndexRoute =
  AuthenticatedIndustryIndexRouteImport.update({
    id: '/industry/',
    path: '/industry/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectorIndexRoute =
  AuthenticatedCollectorIndexRouteImport.update({
    id: '/collector/',
    path: '/collector/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetailerOrdersRoute =
  AuthenticatedRetailerOrdersRouteImport.update({
    id: '/retailer/orders',
    path: '/retailer/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRetailerMarketplaceRoute =
  AuthenticatedRetailerMarketplaceRouteImport.update({
    id: '/retailer/marketplace',
    path: '/retailer/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecyclerProductsRoute =
  AuthenticatedRecyclerProductsRouteImport.update({
    id: '/recycler/products',
    path: '/recycler/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecyclerInventoryRoute =
  AuthenticatedRecyclerInventoryRouteImport.update({
    id: '/recycler/inventory',
    path: '/recycler/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustrySustainabilityRoute =
  AuthenticatedIndustrySustainabilityRouteImport.update({
    id: '/industry/sustainability',
    path: '/industry/sustainability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustryPickupsRoute =
  AuthenticatedIndustryPickupsRouteImport.update({
    id: '/industry/pickups',
    path: '/industry/pickups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustryListingsRoute =
  AuthenticatedIndustryListingsRouteImport.update({
    id: '/industry/listings',
    path: '/industry/listings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectorPickupsRoute =
  AuthenticatedCollectorPickupsRouteImport.update({
    id: '/collector/pickups',
    path: '/collector/pickups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectorJobsRoute =
  AuthenticatedCollectorJobsRouteImport.update({
    id: '/collector/jobs',
    path: '/collector/jobs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/collector/jobs': typeof AuthenticatedCollectorJobsRoute
  '/collector/pickups': typeof AuthenticatedCollectorPickupsRoute
  '/industry/listings': typeof AuthenticatedIndustryListingsRoute
  '/industry/pickups': typeof AuthenticatedIndustryPickupsRoute
  '/industry/sustainability': typeof AuthenticatedIndustrySustainabilityRoute
  '/recycler/inventory': typeof AuthenticatedRecyclerInventoryRoute
  '/recycler/products': typeof AuthenticatedRecyclerProductsRoute
  '/retailer/marketplace': typeof AuthenticatedRetailerMarketplaceRoute
  '/retailer/orders': typeof AuthenticatedRetailerOrdersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/collector/': typeof AuthenticatedCollectorIndexRoute
  '/industry/': typeof AuthenticatedIndustryIndexRoute
  '/recycler/': typeof AuthenticatedRecyclerIndexRoute
  '/retailer/': typeof AuthenticatedRetailerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/collector/jobs': typeof AuthenticatedCollectorJobsRoute
  '/collector/pickups': typeof AuthenticatedCollectorPickupsRoute
  '/industry/listings': typeof AuthenticatedIndustryListingsRoute
  '/industry/pickups': typeof AuthenticatedIndustryPickupsRoute
  '/industry/sustainability': typeof AuthenticatedIndustrySustainabilityRoute
  '/recycler/inventory': typeof AuthenticatedRecyclerInventoryRoute
  '/recycler/products': typeof AuthenticatedRecyclerProductsRoute
  '/retailer/marketplace': typeof AuthenticatedRetailerMarketplaceRoute
  '/retailer/orders': typeof AuthenticatedRetailerOrdersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/collector': typeof AuthenticatedCollectorIndexRoute
  '/industry': typeof AuthenticatedIndustryIndexRoute
  '/recycler': typeof AuthenticatedRecyclerIndexRoute
  '/retailer': typeof AuthenticatedRetailerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/collector/jobs': typeof AuthenticatedCollectorJobsRoute
  '/_authenticated/collector/pickups': typeof AuthenticatedCollectorPickupsRoute
  '/_authenticated/industry/listings': typeof AuthenticatedIndustryListingsRoute
  '/_authenticated/industry/pickups': typeof AuthenticatedIndustryPickupsRoute
  '/_authenticated/industry/sustainability': typeof AuthenticatedIndustrySustainabilityRoute
  '/_authenticated/recycler/inventory': typeof AuthenticatedRecyclerInventoryRoute
  '/_authenticated/recycler/products': typeof AuthenticatedRecyclerProductsRoute
  '/_authenticated/retailer/marketplace': typeof AuthenticatedRetailerMarketplaceRoute
  '/_authenticated/retailer/orders': typeof AuthenticatedRetailerOrdersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/collector/': typeof AuthenticatedCollectorIndexRoute
  '/_authenticated/industry/': typeof AuthenticatedIndustryIndexRoute
  '/_authenticated/recycler/': typeof AuthenticatedRecyclerIndexRoute
  '/_authenticated/retailer/': typeof AuthenticatedRetailerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/admin/users'
    | '/collector/jobs'
    | '/collector/pickups'
    | '/industry/listings'
    | '/industry/pickups'
    | '/industry/sustainability'
    | '/recycler/inventory'
    | '/recycler/products'
    | '/retailer/marketplace'
    | '/retailer/orders'
    | '/admin/'
    | '/collector/'
    | '/industry/'
    | '/recycler/'
    | '/retailer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/admin/users'
    | '/collector/jobs'
    | '/collector/pickups'
    | '/industry/listings'
    | '/industry/pickups'
    | '/industry/sustainability'
    | '/recycler/inventory'
    | '/recycler/products'
    | '/retailer/marketplace'
    | '/retailer/orders'
    | '/admin'
    | '/collector'
    | '/industry'
    | '/recycler'
    | '/retailer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/admin/users'
    | '/_authenticated/collector/jobs'
    | '/_authenticated/collector/pickups'
    | '/_authenticated/industry/listings'
    | '/_authenticated/industry/pickups'
    | '/_authenticated/industry/sustainability'
    | '/_authenticated/recycler/inventory'
    | '/_authenticated/recycler/products'
    | '/_authenticated/retailer/marketplace'
    | '/_authenticated/retailer/orders'
    | '/_authenticated/admin/'
    | '/_authenticated/collector/'
    | '/_authenticated/industry/'
    | '/_authenticated/recycler/'
    | '/_authenticated/retailer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retailer/': {
      id: '/_authenticated/retailer/'
      path: '/retailer'
      fullPath: '/retailer/'
      preLoaderRoute: typeof AuthenticatedRetailerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recycler/': {
      id: '/_authenticated/recycler/'
      path: '/recycler'
      fullPath: '/recycler/'
      preLoaderRoute: typeof AuthenticatedRecyclerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industry/': {
      id: '/_authenticated/industry/'
      path: '/industry'
      fullPath: '/industry/'
      preLoaderRoute: typeof AuthenticatedIndustryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collector/': {
      id: '/_authenticated/collector/'
      path: '/collector'
      fullPath: '/collector/'
      preLoaderRoute: typeof AuthenticatedCollectorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retailer/orders': {
      id: '/_authenticated/retailer/orders'
      path: '/retailer/orders'
      fullPath: '/retailer/orders'
      preLoaderRoute: typeof AuthenticatedRetailerOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retailer/marketplace': {
      id: '/_authenticated/retailer/marketplace'
      path: '/retailer/marketplace'
      fullPath: '/retailer/marketplace'
      preLoaderRoute: typeof AuthenticatedRetailerMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recycler/products': {
      id: '/_authenticated/recycler/products'
      path: '/recycler/products'
      fullPath: '/recycler/products'
      preLoaderRoute: typeof AuthenticatedRecyclerProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recycler/inventory': {
      id: '/_authenticated/recycler/inventory'
      path: '/recycler/inventory'
      fullPath: '/recycler/inventory'
      preLoaderRoute: typeof AuthenticatedRecyclerInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industry/sustainability': {
      id: '/_authenticated/industry/sustainability'
      path: '/industry/sustainability'
      fullPath: '/industry/sustainability'
      preLoaderRoute: typeof AuthenticatedIndustrySustainabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industry/pickups': {
      id: '/_authenticated/industry/pickups'
      path: '/industry/pickups'
      fullPath: '/industry/pickups'
      preLoaderRoute: typeof AuthenticatedIndustryPickupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industry/listings': {
      id: '/_authenticated/industry/listings'
      path: '/industry/listings'
      fullPath: '/industry/listings'
      preLoaderRoute: typeof AuthenticatedIndustryListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collector/pickups': {
      id: '/_authenticated/collector/pickups'
      path: '/collector/pickups'
      fullPath: '/collector/pickups'
      preLoaderRoute: typeof AuthenticatedCollectorPickupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collector/jobs': {
      id: '/_authenticated/collector/jobs'
      path: '/collector/jobs'
      fullPath: '/collector/jobs'
      preLoaderRoute: typeof AuthenticatedCollectorJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCollectorJobsRoute: typeof AuthenticatedCollectorJobsRoute
  AuthenticatedCollectorPickupsRoute: typeof AuthenticatedCollectorPickupsRoute
  AuthenticatedIndustryListingsRoute: typeof AuthenticatedIndustryListingsRoute
  AuthenticatedIndustryPickupsRoute: typeof AuthenticatedIndustryPickupsRoute
  AuthenticatedIndustrySustainabilityRoute: typeof AuthenticatedIndustrySustainabilityRoute
  AuthenticatedRecyclerInventoryRoute: typeof AuthenticatedRecyclerInventoryRoute
  AuthenticatedRecyclerProductsRoute: typeof AuthenticatedRecyclerProductsRoute
  AuthenticatedRetailerMarketplaceRoute: typeof AuthenticatedRetailerMarketplaceRoute
  AuthenticatedRetailerOrdersRoute: typeof AuthenticatedRetailerOrdersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCollectorIndexRoute: typeof AuthenticatedCollectorIndexRoute
  AuthenticatedIndustryIndexRoute: typeof AuthenticatedIndustryIndexRoute
  AuthenticatedRecyclerIndexRoute: typeof AuthenticatedRecyclerIndexRoute
  AuthenticatedRetailerIndexRoute: typeof AuthenticatedRetailerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCollectorJobsRoute: AuthenticatedCollectorJobsRoute,
  AuthenticatedCollectorPickupsRoute: AuthenticatedCollectorPickupsRoute,
  AuthenticatedIndustryListingsRoute: AuthenticatedIndustryListingsRoute,
  AuthenticatedIndustryPickupsRoute: AuthenticatedIndustryPickupsRoute,
  AuthenticatedIndustrySustainabilityRoute:
    AuthenticatedIndustrySustainabilityRoute,
  AuthenticatedRecyclerInventoryRoute: AuthenticatedRecyclerInventoryRoute,
  AuthenticatedRecyclerProductsRoute: AuthenticatedRecyclerProductsRoute,
  AuthenticatedRetailerMarketplaceRoute: AuthenticatedRetailerMarketplaceRoute,
  AuthenticatedRetailerOrdersRoute: AuthenticatedRetailerOrdersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCollectorIndexRoute: AuthenticatedCollectorIndexRoute,
  AuthenticatedIndustryIndexRoute: AuthenticatedIndustryIndexRoute,
  AuthenticatedRecyclerIndexRoute: AuthenticatedRecyclerIndexRoute,
  AuthenticatedRetailerIndexRoute: AuthenticatedRetailerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
